import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"

const mocks = vi.hoisted(() => ({ session: { failed: false, startFailed: false, session: null as unknown, playground: { title: "Playground", steps: [{ id: "1" }, { id: "2" }] }, passedStepIndexes: [] as ReadonlyArray<number>, socketState: "connected", agentConnected: true, verify: vi.fn(), retry: vi.fn() }, readiness: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, paper: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, grade: { isMutating: false, trigger: vi.fn() }, push: vi.fn(), exit: vi.fn() }))
vi.mock("next-intl", () => ({ useTranslations: () => (key: string) => key, useLocale: () => "en" }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: mocks.push }) }))
vi.mock("@/components/layouts/PlaygroundSessionLayout", () => ({ usePlaygroundSession: () => mocks.session }))
vi.mock("@/hooks", () => ({ useQueryMyJobReadinessSwr: () => mocks.readiness }))
vi.mock("@/hooks/swr/useQueryPaperDetailSwr", () => ({ useQueryPaperDetailSwr: () => mocks.paper }))
vi.mock("@/hooks/swr/useMutateGradePaperSwr", () => ({ useMutateGradePaperSwr: () => mocks.grade }))
type PlaygroundStubProps = { readonly state: string; readonly props: { readonly selectedStepIndex: number }; readonly on: { readonly step: (index: number) => void; readonly submit: () => void; readonly leave: () => void; readonly retry: () => void } }
vi.mock("@/components/pages/CoursePlaygroundSessionPage/component", () => ({ CoursePlaygroundSessionPageBase: (input: PlaygroundStubProps) => <><output data-testid="play-state">{input.state}</output><output data-testid="play-index">{input.props.selectedStepIndex}</output><button onClick={() => input.on.step(1)}>step</button><button onClick={input.on.submit}>submit-play</button><button onClick={input.on.leave}>leave-play</button><button onClick={input.on.retry}>retry-play</button></> }))
type ReadinessStubProps = { readonly state: string; readonly props: { readonly courseTitle?: string; readonly metrics?: ReadonlyArray<unknown> }; readonly on: { readonly retry: () => void; readonly act: () => void } }
vi.mock("@/components/blocks/dashboard/JobReadinessWidget/component", () => ({ JobReadinessWidgetBase: (input: ReadinessStubProps) => <><output data-testid="job-state">{input.state}</output><output data-testid="job-course">{input.props.courseTitle}</output><output data-testid="job-metrics">{input.props.metrics?.length}</output><button onClick={input.on.retry}>retry-job</button><button onClick={input.on.act}>act-job</button></> }))
type ExamStubProps = { readonly state: string; readonly props: { readonly stem: string; readonly scoreText: string }; readonly on: { readonly selectAnswer: (id: string) => void; readonly submit: () => void; readonly retry: () => void; readonly forward: () => void; readonly previous: () => void; readonly exit: () => void } }
vi.mock("@/components/blocks/exam/ExamSession/component", () => ({ ExamSessionBase: (input: ExamStubProps) => <><output data-testid="exam-state">{input.state}</output><output data-testid="exam-stem">{input.props.stem}</output><output data-testid="exam-score">{input.props.scoreText}</output><button onClick={() => input.on.selectAnswer("a")}>answer</button><button onClick={input.on.forward}>next-exam</button><button onClick={input.on.previous}>prev-exam</button><button onClick={input.on.submit}>submit-exam</button><button onClick={input.on.retry}>retry-exam</button><button onClick={input.on.exit}>exit-exam</button></> }))
import { CoursePlaygroundSessionPage } from "@/components/pages/CoursePlaygroundSessionPage/index"
import { JobReadinessWidget } from "@/components/blocks/dashboard/JobReadinessWidget/index"
import { ExamSession } from "@/components/blocks/exam/ExamSession/index"

describe("batch 16 connected target states", () => {
    beforeEach(() => { vi.clearAllMocks(); mocks.session.failed = false; mocks.session.startFailed = false; mocks.session.session = { steps: [{ id: "1" }, { id: "2" }] }; mocks.session.passedStepIndexes = []; mocks.session.socketState = "connected"; mocks.session.agentConnected = true; mocks.readiness.data = undefined; mocks.readiness.error = undefined; mocks.paper.data = undefined; mocks.paper.error = undefined; mocks.grade.isMutating = false })
    it("covers playground connecting/reconnecting/live/completed/failed callbacks", () => {
        const view = render(<CoursePlaygroundSessionPage displayId="course" slug="play" />); expect(screen.getByTestId("play-state")).toHaveTextContent("live"); fireEvent.click(screen.getByRole("button", { name: "step" })); expect(screen.getByTestId("play-index")).toHaveTextContent("1"); fireEvent.click(screen.getByRole("button", { name: "submit-play" })); expect(mocks.session.verify).toHaveBeenCalled(); mocks.session.socketState = "reconnecting"; view.rerender(<CoursePlaygroundSessionPage displayId="course" slug="play" />); expect(screen.getByTestId("play-state")).toHaveTextContent("reconnecting"); mocks.session.passedStepIndexes = [0, 1]; view.rerender(<CoursePlaygroundSessionPage displayId="course" slug="play" />); expect(screen.getByTestId("play-state")).toHaveTextContent("completed"); mocks.session.failed = true; view.rerender(<CoursePlaygroundSessionPage displayId="course" slug="play" />); expect(screen.getByTestId("play-state")).toHaveTextContent("failed"); fireEvent.click(screen.getByRole("button", { name: "leave-play" })); fireEvent.click(screen.getByRole("button", { name: "retry-play" })); expect(mocks.push).toHaveBeenCalledWith("/courses/course/learn/playground/play")
    })
    it("covers job readiness failed/empty/ready metrics and actions", async () => {
        const view = render(<JobReadinessWidget />); expect(screen.getByTestId("job-state")).toHaveTextContent("pending"); mocks.readiness.error = new Error("offline"); view.rerender(<JobReadinessWidget />); expect(screen.getByTestId("job-state")).toHaveTextContent("failed"); mocks.readiness.error = undefined; mocks.readiness.data = { tracks: [], foundation: { codingPercentile: null } }; view.rerender(<JobReadinessWidget />); expect(screen.getByTestId("job-state")).toHaveTextContent("empty"); mocks.readiness.data = { foundation: { codingPercentile: 20 }, tracks: [{ courseTitle: "Course", courseSlug: "course", capstoneScore: 80, interviewScore: null, cvScore: 70, depthScore: 60, band: "building" }] }; view.rerender(<JobReadinessWidget />); await waitFor(() => expect(screen.getByTestId("job-state")).toHaveTextContent("ready")); expect(screen.getByTestId("job-metrics")).toHaveTextContent("3"); fireEvent.click(screen.getByRole("button", { name: "act-job" })); fireEvent.click(screen.getByRole("button", { name: "retry-job" })); expect(mocks.push).toHaveBeenCalledWith("/courses/course"); expect(mocks.readiness.mutate).toHaveBeenCalled()
    })
    it("covers exam loading/ready/grading/failure and answer navigation", async () => {
        const view = render(<ExamSession slug="paper" onExit={mocks.exit} />); expect(screen.getByTestId("exam-state")).toHaveTextContent("loading"); mocks.paper.data = { slug: "paper", titleEn: "Paper", titleVi: "Bài", questions: [{ questionId: "q", skill: "arrays", stem: "Choose", optionA: "A", optionB: "B", optionC: "C", optionD: "D" }] }; view.rerender(<ExamSession slug="paper" onExit={mocks.exit} />); await waitFor(() => expect(screen.getByTestId("exam-state")).toHaveTextContent("ready")); fireEvent.click(screen.getByRole("button", { name: "answer" })); mocks.grade.trigger.mockResolvedValue({ data: { gradePaper: { success: true, data: { score: 8, maxScore: 10, answers: [{ questionId: "q", isCorrect: true, stem: "Choose", selected: "A", correct: "A", explanationEn: "Good" }] } } } }); fireEvent.click(screen.getByRole("button", { name: "submit-exam" })); await waitFor(() => expect(screen.getByTestId("exam-state")).toHaveTextContent("graded")); fireEvent.click(screen.getByRole("button", { name: "exit-exam" })); expect(mocks.exit).toHaveBeenCalled()
    })
})
