import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"

const mocks = vi.hoisted(() => ({ weekly: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, recommended: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, lessons: { data: undefined as unknown, error: undefined as unknown }, challenges: { data: undefined as unknown, error: undefined as unknown }, courses: { data: undefined as unknown, error: undefined as unknown }, route: vi.fn(), push: vi.fn(), claim: { trigger: vi.fn() } }))
vi.mock("next-intl", () => ({ useLocale: () => "en", useTranslations: () => (key: string) => key }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: mocks.push }) }))
vi.mock("@/hooks", () => ({ useQueryWeeklyChallengeSwr: () => mocks.weekly, useMutateClaimWeeklyChallengeRewardSwr: () => mocks.claim, useQueryRecommendedCoursesSwr: () => mocks.recommended, useQueryMyLearnedLessonsSwr: () => mocks.lessons, useQueryMyInProgressChallengesSwr: () => mocks.challenges, useQueryMyCoursesSwr: () => mocks.courses }))
vi.mock("@/modules/api/graphql/queries/query-resolve-route", () => ({ queryResolveRoute: mocks.route }))
type WeeklyStubProps = { readonly state: string; readonly props: { readonly title?: string; readonly claimed?: boolean; readonly viewerPassed?: boolean }; readonly on: { readonly act: () => void; readonly retry: () => void } }
vi.mock("@/components/blocks/dashboard/WeeklyChallengeCard/component", () => ({ WeeklyChallengeCardBase: (input: WeeklyStubProps) => <><output data-testid="weekly-state">{input.state}</output><output data-testid="weekly-title">{input.props.title}</output><button onClick={input.on.act}>weekly-act</button><button onClick={input.on.retry}>weekly-retry</button></> }))
type ContinueStubProps = { readonly state: string; readonly props: { readonly items?: ReadonlyArray<{ readonly id: string }> }; readonly on?: { readonly act?: () => void; readonly resume?: (id: string) => void } }
vi.mock("@/components/blocks/dashboard/ContinueLearning/component", () => ({ ContinueLearningBase: (input: ContinueStubProps) => <><output data-testid="continue-state">{input.state}</output><output data-testid="continue-items">{input.props.items?.map((item) => item.id).join("|")}</output><button onClick={input.on?.act}>browse</button><button onClick={() => input.on?.resume?.("lesson")}>resume</button></> }))
type RecommendedStubProps = { readonly state: string; readonly props: { readonly rows: ReadonlyArray<{ readonly id: string; readonly discount?: string }> }; readonly on?: Record<string, () => void> }
vi.mock("@/components/blocks/dashboard/RecommendedCourses/component", () => ({ RecommendedCoursesBase: (input: RecommendedStubProps) => <><output data-testid="recommended-state">{input.state}</output><output data-testid="recommended-rows">{input.props.rows.map((row) => `${row.id}:${row.discount ?? "none"}`).join("|")}</output><button onClick={() => { const key = Object.keys(input.on ?? {}).find((item) => item.startsWith("open:")); if (key) input.on?.[key]?.() }}>open-recommended</button><button onClick={() => { const key = Object.keys(input.on ?? {}).find((item) => item.startsWith("priceDetail:")); if (key) input.on?.[key]?.() }}>price-recommended</button><button onClick={input.on?.retry}>retry-recommended</button></> }))
import { WeeklyChallengeCard } from "@/components/blocks/dashboard/WeeklyChallengeCard/index"
import { ContinueLearning } from "@/components/blocks/dashboard/ContinueLearning/index"
import { RecommendedCourses } from "@/components/blocks/dashboard/RecommendedCourses/index"

describe("dashboard measured target blocks", () => {
    beforeEach(() => { vi.clearAllMocks(); mocks.weekly.data = undefined; mocks.weekly.error = undefined; mocks.recommended.data = undefined; mocks.recommended.error = undefined; mocks.lessons.data = undefined; mocks.lessons.error = undefined; mocks.challenges.data = undefined; mocks.challenges.error = undefined; mocks.courses.data = undefined; mocks.courses.error = undefined })
    it("covers weekly challenge pending/failed/empty/ready claim and route", async () => {
        const view = render(<WeeklyChallengeCard />); expect(screen.getByTestId("weekly-state")).toHaveTextContent("pending")
        mocks.weekly.error = new Error("offline"); view.rerender(<WeeklyChallengeCard />); expect(screen.getByTestId("weekly-state")).toHaveTextContent("failed")
        mocks.weekly.error = undefined; mocks.weekly.data = null; view.rerender(<WeeklyChallengeCard />); expect(screen.getByTestId("weekly-state")).toHaveTextContent("empty")
        mocks.weekly.data = { title: "Weekly", weekEndAt: new Date(Date.now() + 3600000).toISOString(), challengeGlobalId: "challenge", viewerPassed: true, claimed: false, coinReward: 20, passedCount: 3, leaderboard: [{ username: "Ada", passedAt: new Date().toISOString() }] }; mocks.claim.trigger.mockResolvedValue(undefined); mocks.weekly.mutate.mockResolvedValue(undefined); view.rerender(<WeeklyChallengeCard />); await waitFor(() => expect(screen.getByTestId("weekly-state")).toHaveTextContent("ready")); fireEvent.click(screen.getByRole("button", { name: "weekly-act" })); await waitFor(() => expect(mocks.claim.trigger).toHaveBeenCalled()); expect(mocks.weekly.mutate).toHaveBeenCalled()
        mocks.weekly.data = { title: "Weekly", weekEndAt: new Date(Date.now() + 3600000).toISOString(), challengeGlobalId: "challenge", viewerPassed: true, claimed: true, coinReward: 20, passedCount: 3, leaderboard: [] }; view.rerender(<WeeklyChallengeCard />); fireEvent.click(screen.getByRole("button", { name: "weekly-act" })); expect(mocks.push).toHaveBeenCalledWith("/challenges/challenge")
    })
    it("covers ContinueLearning failed/pending/ready/onboarding/empty and routes", async () => {
        const view = render(<ContinueLearning />); expect(screen.getByTestId("continue-state")).toHaveTextContent("pending")
        mocks.lessons.error = new Error("offline"); view.rerender(<ContinueLearning />); expect(screen.getByTestId("continue-state")).toHaveTextContent("failed")
        mocks.lessons.error = undefined; mocks.lessons.data = [{ globalId: "lesson", label: "Lesson" }]; mocks.challenges.data = [{ globalId: "challenge", label: "Challenge" }]; mocks.courses.data = []; mocks.route.mockResolvedValue({ data: { resolveRoute: { data: { path: "/en/lesson" } } } }); view.rerender(<ContinueLearning />); await waitFor(() => expect(screen.getByTestId("continue-state")).toHaveTextContent("ready")); fireEvent.click(screen.getByRole("button", { name: "resume" })); await waitFor(() => expect(mocks.push).toHaveBeenCalledWith("/lesson"))
        mocks.lessons.data = []; mocks.challenges.data = []; mocks.courses.data = []; view.rerender(<ContinueLearning />); expect(screen.getByTestId("continue-state")).toHaveTextContent("onboarding"); fireEvent.click(screen.getByRole("button", { name: "browse" })); expect(mocks.push).toHaveBeenCalledWith("/courses")
        mocks.courses.data = [{ globalId: "course" }]; view.rerender(<ContinueLearning />); expect(screen.getByTestId("continue-state")).toHaveTextContent("empty")
    })
    it("covers RecommendedCourses pending/failed/hidden/discounted ready", async () => {
        const priceDetail = vi.fn(); const view = render(<RecommendedCourses onOpenPriceDetail={priceDetail} />); expect(screen.getByTestId("recommended-state")).toHaveTextContent("pending")
        mocks.recommended.error = new Error("offline"); view.rerender(<RecommendedCourses onOpenPriceDetail={priceDetail} />); expect(screen.getByTestId("recommended-state")).toHaveTextContent("failed")
        mocks.recommended.error = undefined; mocks.recommended.data = []; view.rerender(<RecommendedCourses onOpenPriceDetail={priceDetail} />); expect(screen.getByTestId("recommended-state")).toHaveTextContent("hidden")
        mocks.recommended.data = [{ displayId: "course", title: "Course", thumbnailUrl: null, discountedPriceVnd: 500, originalPriceVnd: 1000, discountPercent: 50, discountReason: "enrolledCount", enrolledCount: 2 }]; view.rerender(<RecommendedCourses onOpenPriceDetail={priceDetail} />); await waitFor(() => expect(screen.getByTestId("recommended-state")).toHaveTextContent("ready")); expect(screen.getByTestId("recommended-rows")).toHaveTextContent("course:−50%"); fireEvent.click(screen.getByRole("button", { name: "open-recommended" })); fireEvent.click(screen.getByRole("button", { name: "price-recommended" })); expect(mocks.push).toHaveBeenCalledWith("/courses/course"); expect(priceDetail).toHaveBeenCalledWith("course")
    })
})
