import { beforeEach, describe, expect, it, vi } from "vitest"
const mocks = vi.hoisted(() => ({ endpoint: "", create: vi.fn(), joinById: vi.fn(), joinOrCreate: vi.fn(), consumeSeatReservation: vi.fn(), lobbyMessage: undefined as ((message: { reservation: unknown }) => void) | undefined, room: undefined as { roomId: string; onMessage: ReturnType<typeof vi.fn>; onError: ReturnType<typeof vi.fn>; onLeave: ReturnType<typeof vi.fn>; send: ReturnType<typeof vi.fn>; leave: ReturnType<typeof vi.fn> } | undefined }))
vi.mock("colyseus.js", () => ({ Client: class { constructor(endpoint: string) { mocks.endpoint = endpoint } create = mocks.create; joinById = mocks.joinById; joinOrCreate = mocks.joinOrCreate; consumeSeatReservation = mocks.consumeSeatReservation } }))
import { GameClient } from "./client"
describe("GameClient", () => {
    beforeEach(() => {
        mocks.create.mockReset(); mocks.joinById.mockReset(); mocks.joinOrCreate.mockReset(); mocks.consumeSeatReservation.mockReset(); mocks.lobbyMessage = undefined
        const onError = Object.assign(vi.fn(), { remove: vi.fn() }); const onLeave = Object.assign(vi.fn(), { remove: vi.fn() })
        mocks.room = { roomId: "room", onMessage: vi.fn((_: string, listener: unknown) => { return () => listener }), onError, onLeave, send: vi.fn(), leave: vi.fn().mockResolvedValue(undefined) }
        mocks.create.mockResolvedValue(mocks.room); mocks.joinById.mockResolvedValue(mocks.room); mocks.consumeSeatReservation.mockResolvedValue(mocks.room)
    })
    it("sends token, uppercase mode and character to the separate endpoint", async () => { const client = new GameClient("ws://localhost:2638"); await client.connect({ game: "match_pairs", mode: "COUPLE", character: "MIA" }, "token"); expect(mocks.endpoint).toBe("ws://localhost:2638"); expect(mocks.create).toHaveBeenCalledWith("match_pairs", { token: "token", mode: "COUPLE", character: "MIA" }) })
    it("joins a room by code and wraps subscriptions, sends and memoized leave", async () => {
        const client = new GameClient("ws://localhost:2638"); const connection = await client.connect({ game: "vocab_defense", mode: "SOLO", character: "MAX", roomCode: "ABC" }, "token")
        expect(mocks.joinById).toHaveBeenCalledWith("ABC", { token: "token", mode: "SOLO", character: "MAX", roomCode: "ABC" })
        const listener = vi.fn(); const unsubscribe = connection.onSnapshot(listener); connection.onAnswerResult(listener); connection.onLeave(listener); connection.answer(2); connection.restart(); const first = connection.leave(); const second = connection.leave(); await Promise.all([first, second]); expect(first).toBe(second); expect(mocks.room?.send).toHaveBeenCalledWith("answer", { index: 2 }); expect(mocks.room?.send).toHaveBeenCalledWith("restart"); expect(mocks.room?.leave).toHaveBeenCalledOnce(); unsubscribe()
    })
    it("maps transport errors and removes error listeners", async () => {
        const client = new GameClient(); const connection = await client.connect({ game: "match_pairs", mode: "SOLO", character: "MIA" }, "token"); const listener = vi.fn(); const off = connection.onError(listener); const callback = mocks.room?.onError.mock.calls[0][0] as (code: number, message?: string) => void; callback(401, "membership required"); callback(500, "websocket network down"); callback(500, "unexpected"); expect(listener).toHaveBeenNthCalledWith(1, { kind: "membership", message: "membership required" }); expect(listener).toHaveBeenNthCalledWith(2, { kind: "network", message: "websocket network down" }); expect(listener).toHaveBeenNthCalledWith(3, { kind: "unknown", message: "unexpected" }); off(); expect(mocks.room?.onError.remove).toHaveBeenCalledWith(callback)
    })
    it("completes team matchmaking from a reservation and always leaves the lobby", async () => {
        const lobby = { onMessage: vi.fn((_name: string, callback: (message: { reservation: unknown }) => void) => { mocks.lobbyMessage = callback; return vi.fn() }), onError: vi.fn(), leave: vi.fn().mockResolvedValue(undefined) }; mocks.joinOrCreate.mockResolvedValue(lobby); const client = new GameClient(); const pending = client.connect({ game: "match_pairs", mode: "TEAM2V2", character: "MIA" }, "token"); await Promise.resolve(); mocks.lobbyMessage?.({ reservation: { seat: "reserved" } }); await pending; expect(mocks.joinOrCreate).toHaveBeenCalledWith("team_matchmaking", { token: "token", mode: "TEAM2V2", character: "MIA", game: "match_pairs" }); expect(mocks.consumeSeatReservation).toHaveBeenCalledWith({ seat: "reserved" }); expect(lobby.leave).toHaveBeenCalledWith(true)
    })
    it("classifies every public transport category", () => { expect(GameClient.classifyError(new Error("auth token expired")).kind).toBe("auth"); expect(GameClient.classifyError("room not found").kind).toBe("room-not-found"); expect(GameClient.classifyError("connect failed").kind).toBe("network"); expect(GameClient.classifyError("entitlement missing").kind).toBe("membership") })
})
