import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ token: "token" as string | undefined, query: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, trigger: vi.fn(), requireSignIn: vi.fn(), exit: vi.fn() }))
vi.mock("next-intl", () => ({ useTranslations: () => (key: string) => key }))
vi.mock("@/hooks/auth/useSessionToken", () => ({ useSessionToken: () => m.token }))
vi.mock("@/hooks", () => ({ useQueryPhrasePracticeSwr: () => m.query }))
vi.mock("swr/mutation", () => ({ default: () => ({ isMutating: false, trigger: m.trigger }) }))
type MockPracticeProps = { readonly state: string; readonly on: Record<string, ((...args: ReadonlyArray<unknown>) => unknown) | undefined> }
vi.mock("./component", () => ({ PhrasePracticeBase: ({ state, on }: MockPracticeProps) => <><output data-testid="state">{state}</output><button onClick={() => on.select?.("p1")}>select</button><button onClick={on.previous}>previous</button><button onClick={on.next}>next</button><button onClick={on.submit}>submit</button><button onClick={on.retry}>retry</button><button onClick={on.repeat}>repeat</button><button onClick={on.exit}>exit</button></> }))
import { PhrasePractice } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.token = "token"; m.query.data = undefined; m.query.error = undefined; m.trigger.mockReset() })
describe("PhrasePractice connected state", () => {
    it("renders pending, failed and empty states", () => { const view = render(<PhrasePractice slug="topic" onRequireSignIn={m.requireSignIn} onExit={m.exit} />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.query.error = new Error("offline"); view.rerender(<PhrasePractice slug="topic" onRequireSignIn={m.requireSignIn} onExit={m.exit} />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.query.error = undefined; m.query.data = []; view.rerender(<PhrasePractice slug="topic" onRequireSignIn={m.requireSignIn} onExit={m.exit} />); expect(screen.getByTestId("state")).toHaveTextContent("empty") })
    it("requires sign-in before submitting without a token and retries/exits", () => { m.query.data = [{ promptPhraseId: "p1", meaningVi: "xin chao", options: [] }]; m.token = undefined; render(<PhrasePractice slug="topic" onRequireSignIn={m.requireSignIn} onExit={m.exit} />); fireEvent.click(screen.getByText("submit")); fireEvent.click(screen.getByText("retry")); fireEvent.click(screen.getByText("exit")); expect(m.requireSignIn).toHaveBeenCalled(); expect(m.query.mutate).toHaveBeenCalled(); expect(m.exit).toHaveBeenCalled() })
    it("selects phrases, navigates positions and records a successful result", async () => { m.query.data = [{ promptPhraseId: "p1", meaningVi: "hello", options: [{ phraseId: "p1", text: "xin chao" }] }, { promptPhraseId: "p2", meaningVi: "bye", options: [{ phraseId: "p2", text: "tam biet" }] }]; m.trigger.mockResolvedValue({ data: { recordPractice: { success: true, data: { phrasesStudied: 2, phrasesKnown: 1 } } } }); render(<PhrasePractice slug="topic" onRequireSignIn={m.requireSignIn} onExit={m.exit} />); fireEvent.click(screen.getByText("select")); fireEvent.click(screen.getByText("next")); fireEvent.click(screen.getByText("previous")); fireEvent.click(screen.getByText("submit")); await waitFor(() => expect(m.trigger).toHaveBeenCalledWith({ topicSlug: "topic", results: [{ phraseId: "p1", correct: true }, { phraseId: "p2", correct: false }] })); expect(screen.getByTestId("state")).toHaveTextContent("result"); fireEvent.click(screen.getByText("repeat")); expect(screen.getByTestId("state")).toHaveTextContent("answering") })
    it("attempts a failed record mutation without losing the answering surface", async () => { m.query.data = [{ promptPhraseId: "p1", meaningVi: "hello", options: [] }]; m.trigger.mockRejectedValue(new Error("offline")); render(<PhrasePractice slug="topic" onRequireSignIn={m.requireSignIn} onExit={m.exit} />); fireEvent.click(screen.getByText("submit")); await waitFor(() => expect(m.trigger).toHaveBeenCalledOnce()); expect(screen.getByTestId("state")).toHaveTextContent("answering") })
})
