coverage:
  status:
    project:
      default:
        target: 80%
        informational: false
    patch:
      default:
        target: 90%
        informational: false

codecov:
  require_ci_to_pass: true

comment:
  require_changes: true
