type TestPageInput = { state: string; on: Record<string, (...args: ReadonlyArray<unknown>) => unknown> }
import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ token: "token" as string | undefined, cart: { data: undefined as unknown, error: undefined as unknown, isLoading: false, mutate: vi.fn() }, preview: { data: undefined as unknown, error: undefined as unknown }, clearing: { trigger: vi.fn() }, checkout: { trigger: vi.fn() }, push: vi.fn(), mutate: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => "en", useTranslations: () => (key: string) => key }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: m.push }) }))
vi.mock("@/hooks/auth/useSessionToken", () => ({ useSessionToken: () => m.token }))
vi.mock("swr", () => ({ useSWRConfig: () => ({ mutate: m.mutate }) }))
vi.mock("@/hooks", () => ({ useQueryMyCartSwr: () => m.cart, useQueryCoursesCheckoutPreviewSwr: () => m.preview, useMutateClearCartSwr: () => m.clearing, useMutateCoursesCheckoutSwr: () => m.checkout }))
vi.mock("./component", () => ({ _CartPage: ({ state, on }: TestPageInput) => <><output data-testid="state">{state}</output><button onClick={on.checkout}>checkout</button><button onClick={on.clearAll}>clear</button><button onClick={on.goHome}>home</button><button onClick={on.browse}>browse</button></> }))
import { CartPage } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.token = "token"; m.cart.data = undefined; m.cart.error = undefined; m.cart.isLoading = false; m.preview.data = undefined; m.preview.error = undefined; m.clearing.trigger.mockResolvedValue({ data: { clearCart: { success: true } } }); m.checkout.trigger.mockResolvedValue({ data: { coursesCheckout: { data: null } } }) })
describe("CartPage route", () => {
    it("resolves signed-out, pending, failed, empty and ready cart states", () => { m.token = undefined; const view = render(<CartPage />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); fireEvent.click(screen.getByText("browse")); expect(m.push).toHaveBeenCalledWith("/authentication"); m.token = "token"; m.cart.isLoading = true; view.rerender(<CartPage />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.cart.isLoading = false; m.cart.data = []; m.preview.data = { lines: [], totalListVnd: 0, totalChargedVnd: 0, savingsVnd: 0, installmentOptions: [] }; view.rerender(<CartPage />); expect(screen.getByTestId("state")).toHaveTextContent("empty"); m.cart.error = new Error("offline"); view.rerender(<CartPage />); expect(screen.getByTestId("state")).toHaveTextContent("failed") })
    it("joins priced lines and forwards checkout, clear and navigation actions", async () => { m.cart.data = [{ courseId: "c1", course: { title: "Course", coverImageUrl: null } }]; m.preview.data = { lines: [{ courseId: "c1", chargedVnd: 80000, listVnd: 100000, discountPercent: 20 }], totalListVnd: 100000, totalChargedVnd: 80000, savingsVnd: 20000, installmentOptions: [{ monthlyAmountVnd: 40000 }] }; render(<CartPage />); expect(screen.getByTestId("state")).toHaveTextContent("ready"); fireEvent.click(screen.getByText("checkout")); fireEvent.click(screen.getByText("clear")); fireEvent.click(screen.getByText("home")); fireEvent.click(screen.getByText("browse")); await waitFor(() => expect(m.checkout.trigger).toHaveBeenCalled()); expect(m.clearing.trigger).toHaveBeenCalledOnce(); expect(m.mutate).toHaveBeenCalled(); expect(m.push).toHaveBeenCalledWith("/dashboard"); expect(m.push).toHaveBeenCalledWith("/courses") })
    it("reports pricing and clear failures without losing the cart", async () => { m.cart.data = [{ courseId: "c1", course: { title: "Course", coverImageUrl: null } }]; m.preview.error = new Error("pricing"); m.preview.data = null; m.clearing.trigger.mockResolvedValue({ data: { clearCart: { success: false } } }); render(<CartPage />); fireEvent.click(screen.getByText("clear")); await waitFor(() => expect(m.clearing.trigger).toHaveBeenCalledOnce()); expect(screen.getByTestId("state")).toHaveTextContent("ready") })
})
