import { fireEvent, render, screen } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ project: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, push: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => "en" }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: m.push }) }))
vi.mock("@/hooks/swr/useQueryCoursePersonalProjectSwr", () => ({ useQueryCoursePersonalProjectSwr: () => m.project }))
type ProjectProps = { readonly state: string; readonly on: { readonly openTask: (id: string) => void; readonly retry: () => void } }
vi.mock("./component", () => ({ CoursePersonalProjectPageBase: ({ state, on }: ProjectProps) => <><output data-testid="state">{state}</output><button onClick={() => on.openTask("task")}>open</button><button onClick={on.retry}>retry</button></> }))
import { CoursePersonalProjectPage } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.project.data = undefined; m.project.error = undefined })
describe("CoursePersonalProjectPage", () => { it("settles pending, failed and empty", () => { const view = render(<CoursePersonalProjectPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.project.error = new Error("offline"); view.rerender(<CoursePersonalProjectPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.project.error = undefined; m.project.data = { milestones: [], progress: { tasksCompleted: 0, tasksTotal: 0, completionPercent: 0 } }; view.rerender(<CoursePersonalProjectPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("empty") }); it("renders ready tasks and routes open/retry", () => { m.project.data = { milestones: [{ orderIndex: 0, title: "Milestone", tasks: [{ id: "task", title: "Task", completed: false }] }], progress: { tasksCompleted: 0, tasksTotal: 1, completionPercent: 0 }, currentTask: { kind: "milestoneTask", id: "task" } }; render(<CoursePersonalProjectPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("ready"); fireEvent.click(screen.getByText("open")); fireEvent.click(screen.getByText("retry")); expect(m.push).toHaveBeenCalledWith("/courses/course/learn/personal-project/tasks/task"); expect(m.project.mutate).toHaveBeenCalled() }) })
