type TestPageInput = { state: string; on: Record<string, (...args: ReadonlyArray<unknown>) => unknown> }
type QaQueryInput = { readonly parentCommentId?: string }
import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ locale: "en", course: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, questions: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, replies: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, create: { isMutating: false, trigger: vi.fn() }, push: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => m.locale }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: m.push }) }))
vi.mock("@/hooks/swr/useQueryCourseSwr", () => ({ useQueryCourseSwr: () => m.course }))
vi.mock("@/hooks/swr/useQueryCourseQaCommentsSwr", () => ({ useQueryCourseQaCommentsSwr: (input: QaQueryInput) => input.parentCommentId === undefined ? m.questions : m.replies }))
vi.mock("@/hooks/swr/useMutateCreateCourseQuestionSwr", () => ({ useMutateCreateCourseQuestionSwr: () => m.create }))
vi.mock("./component", () => ({ _CourseQaPage: ({ state, on }: TestPageInput) => <><output data-testid="state">{state}</output><button onClick={on.course}>course</button><button onClick={() => on.search("help")}>search</button><button onClick={() => on.changeDraft("How does this work?")}>draft</button><button onClick={on.ask}>ask</button><button onClick={() => on.openThread("q1")}>thread</button><button onClick={on.closeThread}>close</button><button onClick={on.retry}>retry</button></> }))
import { CourseQaPage } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.locale = "en"; m.course.data = undefined; m.course.error = undefined; m.questions.data = undefined; m.questions.error = undefined; m.replies.data = undefined; m.replies.error = undefined; m.create.isMutating = false; m.create.trigger.mockResolvedValue({ data: { createComment: { success: true } } }) })
describe("CourseQaPage route", () => {
    it("resolves pending, empty, failed and ready Q&A states with actions", async () => { const view = render(<CourseQaPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.course.data = { id: "course-id", title: "Course" }; m.questions.data = { comments: [] }; m.replies.data = { comments: [] }; view.rerender(<CourseQaPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("empty"); m.questions.error = new Error("offline"); view.rerender(<CourseQaPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.questions.error = undefined; m.questions.data = { comments: [{ id: "q1", body: "Need help", replyCount: 1, isFounderAuthor: true, createdAt: "2025-01-01T00:00:00Z", author: { username: "Ada" } }] }; m.replies.data = { comments: [{ id: "r1", body: "Answer", replyCount: 0, isFounderAuthor: false, createdAt: "2025-01-01T00:00:00Z", author: { username: "Lin" } }] }; view.rerender(<CourseQaPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("ready"); fireEvent.click(screen.getByText("course")); fireEvent.click(screen.getByText("search")); fireEvent.click(screen.getByText("thread")); fireEvent.click(screen.getByText("draft")); fireEvent.click(screen.getByText("ask")); await waitFor(() => expect(m.create.trigger).toHaveBeenCalledWith({ courseId: "course-id", body: "How does this work?" })); fireEvent.click(screen.getByText("close")); fireEvent.click(screen.getByText("retry")); expect(m.push).toHaveBeenCalledWith("/courses/course"); expect(m.questions.mutate).toHaveBeenCalled() })
    it("keeps Vietnamese search and failed replies distinct", () => { m.locale = "vi"; m.course.data = { id: "course-id" }; m.questions.data = { comments: [{ id: "q1", body: "Câu hỏi", replyCount: 0, isFounderAuthor: false, createdAt: "2025-01-01T00:00:00Z", author: { username: "An" } }] }; m.replies.data = { comments: [] }; const view = render(<CourseQaPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("ready"); fireEvent.click(screen.getByText("thread")); m.replies.error = new Error("offline"); view.rerender(<CourseQaPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("failed") })
})
