type TestPageInput = { state: string; on: Record<string, (...args: ReadonlyArray<unknown>) => unknown> }
import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ locale: "en", course: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, decks: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, due: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, stats: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, deckProgress: { data: undefined as unknown }, dueProgress: { data: undefined as unknown }, start: { error: undefined as unknown, trigger: vi.fn() }, push: vi.fn(), replace: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => m.locale, useTranslations: () => (key: string) => key }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: m.push, replace: m.replace }) }))
vi.mock("@/hooks/swr/useQueryCourseSwr", () => ({ useQueryCourseSwr: () => m.course }))
vi.mock("@/hooks/swr/useQueryFlashcardDecksByCourseSwr", () => ({ useQueryFlashcardDecksByCourseSwr: () => m.decks, useQueryMyDueFlashcardsSwr: () => m.due }))
vi.mock("@/hooks/swr/useQueryMyFlashcardStatsSwr", () => ({ useQueryMyFlashcardStatsSwr: () => m.stats }))
vi.mock("@/hooks/swr/useQueryMyInProgressFlashcardSessionSwr", () => ({ useQueryMyInProgressFlashcardSessionSwr: (input: unknown) => String(input).includes("due") ? m.dueProgress : m.deckProgress }))
vi.mock("@/hooks/swr/useMutateStartFlashcardSessionSwr", () => ({ useMutateStartFlashcardSessionSwr: () => m.start }))
vi.mock("./component", () => ({ _CourseFlashcardsReviewPage: ({ state, on }: TestPageInput) => <><output data-testid="state">{state}</output><button onClick={on.openQuiz}>quiz</button><button onClick={on.startDue}>due</button><button onClick={() => on.startDeck("deck1")}>deck</button><button onClick={() => on.resume("session1")}>resume</button><button onClick={on.retry}>retry</button></> }))
import { CourseFlashcardsReviewPage } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.locale = "en"; m.course.data = undefined; m.course.error = undefined; m.decks.data = undefined; m.decks.error = undefined; m.due.data = undefined; m.due.error = undefined; m.stats.data = undefined; m.stats.error = undefined; m.deckProgress.data = undefined; m.dueProgress.data = undefined; m.start.error = undefined; m.start.trigger.mockResolvedValue({ sessionId: "session1" }) })
describe("CourseFlashcardsReviewPage route", () => {
    it("renders pending, failed, empty and ready states with deck actions", async () => { const view = render(<CourseFlashcardsReviewPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.course.data = { id: "course-id" }; m.decks.data = []; m.due.data = { dueCount: 0, cards: [] }; m.stats.data = { currentStreak: 1, retentionRate: 80 }; view.rerender(<CourseFlashcardsReviewPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("empty"); m.decks.error = new Error("offline"); view.rerender(<CourseFlashcardsReviewPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.decks.error = undefined; m.decks.data = [{ id: "deck1", title: "Deck", description: "Cards", difficulty: "easy", cards: [{ id: "card1" }], dueCount: 2, masteredCount: 1 }]; m.due.data = { dueCount: 1, cards: [{ cardId: "card2" }] }; m.deckProgress.data = { sessionId: "deck-session" }; m.dueProgress.data = { sessionId: "due-session" }; view.rerender(<CourseFlashcardsReviewPage displayId="course" />); expect(screen.getByTestId("state")).toHaveTextContent("ready"); fireEvent.click(screen.getByText("quiz")); fireEvent.click(screen.getByText("deck")); fireEvent.click(screen.getByText("due")); fireEvent.click(screen.getByText("resume")); fireEvent.click(screen.getByText("retry")); await waitFor(() => expect(m.start.trigger).toHaveBeenCalled()); expect(m.push).toHaveBeenCalledWith("/courses/course/learn/flashcards/quiz"); expect(m.decks.mutate).toHaveBeenCalledOnce() })
    it("uses Vietnamese labels and keeps due start guarded while deck starts", async () => { m.locale = "vi"; m.course.data = { id: "course-id" }; m.decks.data = [{ id: "deck1", title: "Deck", description: null, difficulty: "hard", cards: [], dueCount: 0, masteredCount: 0 }]; m.due.data = { dueCount: 0, cards: [] }; m.stats.data = { currentStreak: 0, retentionRate: 0 }; m.deckProgress.data = null; m.dueProgress.data = null; render(<CourseFlashcardsReviewPage displayId="course" />); fireEvent.click(screen.getByText("deck")); fireEvent.click(screen.getByText("due")); await new Promise((resolve) => setTimeout(resolve, 0)); expect(m.start.trigger).toHaveBeenCalledOnce() })
})
