type TestPageInput = { state: string; on: Record<string, (...args: ReadonlyArray<unknown>) => unknown> }
import { fireEvent, render, screen } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ locale: "en", course: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, company: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, consultants: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, push: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => m.locale }))
vi.mock("@/i18n/navigation", () => ({ useRouter: () => ({ push: m.push }) }))
vi.mock("@/hooks/swr/useQueryCourseSwr", () => ({ useQueryCourseSwr: () => m.course }))
vi.mock("@/hooks/swr/useQueryHeadhuntingCompanySwr", () => ({ useQueryHeadhuntingCompanySwr: () => m.company }))
vi.mock("@/hooks/swr/useQueryConsultantsSwr", () => ({ useQueryConsultantsSwr: () => m.consultants }))
vi.mock("./component", () => ({ CourseHeadhuntingCompanyPageBase: ({ state, on }: TestPageInput) => <><output data-testid="state">{state}</output><button onClick={on.course}>course</button><button onClick={on.back}>back</button><button onClick={on.retry}>retry</button><button onClick={on.companyContact}>company-contact</button><button onClick={on["contact:consult"]}>consult-contact</button></> }))
import { CourseHeadhuntingCompanyPage } from "./index"
beforeEach(() => { vi.clearAllMocks(); window.open = vi.fn(); m.locale = "en"; m.course.data = undefined; m.course.error = undefined; m.company.data = undefined; m.company.error = undefined; m.consultants.data = undefined; m.consultants.error = undefined })
describe("CourseHeadhuntingCompanyPage route", () => {
    it("resolves pending, not-found, failed and ready company states", () => { const view = render(<CourseHeadhuntingCompanyPage displayId="course" companyId="company" />); expect(screen.getByTestId("state")).toHaveTextContent("pending"); m.course.data = { id: "course", title: "Course" }; m.company.data = null; m.consultants.data = { data: [] }; view.rerender(<CourseHeadhuntingCompanyPage displayId="course" companyId="company" />); expect(screen.getByTestId("state")).toHaveTextContent("not-found"); m.company.error = new Error("offline"); view.rerender(<CourseHeadhuntingCompanyPage displayId="course" companyId="company" />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.company.error = undefined; m.company.data = { id: "company", title: "Alpha", description: "Team", email: null, websiteUrl: "https://alpha.example", linkedinUrl: null, address: "Remote" }; m.consultants.data = { data: [{ id: "consult", fullName: "Lin", jobTitle: "Recruiter", description: null, contactUnlocked: true, cvScoreUnlockThreshold: 80, email: null, linkedinUrl: "https://linkedin.com/in/lin", phoneNumber: null, zaloNumber: null }] }; view.rerender(<CourseHeadhuntingCompanyPage displayId="course" companyId="company" />); expect(screen.getByTestId("state")).toHaveTextContent("ready"); fireEvent.click(screen.getByText("course")); fireEvent.click(screen.getByText("back")); fireEvent.click(screen.getByText("retry")); fireEvent.click(screen.getByText("company-contact")); fireEvent.click(screen.getByText("consult-contact")); expect(m.push).toHaveBeenCalledWith("/courses/course"); expect(m.push).toHaveBeenCalledWith("/courses/course/learn/headhuntings"); expect(m.consultants.mutate).toHaveBeenCalledOnce() })
    it("renders Vietnamese locked consultant copy and empty roster", () => { m.locale = "vi"; m.course.data = { id: "course", title: "Course" }; m.company.data = { id: "company", title: "Alpha", email: null, websiteUrl: null, linkedinUrl: null }; m.consultants.data = { data: [{ id: "locked", fullName: "Recruiter", jobTitle: null, description: "Description", contactUnlocked: false, cvScoreUnlockThreshold: 90, email: null, linkedinUrl: null, phoneNumber: null, zaloNumber: null }] }; render(<CourseHeadhuntingCompanyPage displayId="course" companyId="company" />); expect(screen.getByTestId("state")).toHaveTextContent("ready") })
})
