import { fireEvent, render, screen } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ paper: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, grade: { isMutating: false, trigger: vi.fn() }, exit: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => "en", useTranslations: () => (key: string) => key }))
vi.mock("@/hooks/swr/useQueryPaperDetailSwr", () => ({ useQueryPaperDetailSwr: () => m.paper }))
vi.mock("@/hooks/swr/useMutateGradePaperSwr", () => ({ useMutateGradePaperSwr: () => m.grade }))
type ExamProps = { readonly state: string; readonly on: Record<string, (...args: ReadonlyArray<unknown>) => void> }
vi.mock("./component", () => ({ ExamSessionBase: ({ state, on }: ExamProps) => <><output data-testid="state">{state}</output><button onClick={() => on.selectAnswer("a")}>answer</button><button onClick={on.submit}>submit</button><button onClick={on.retry}>retry</button><button onClick={on.exit}>exit</button></> }))
import { ExamSession } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.paper.data = undefined; m.paper.error = undefined; m.grade.isMutating = false })
describe("ExamSession", () => { it("settles loading, failed and ready", () => { const view = render(<ExamSession slug="paper" onExit={m.exit} />); expect(screen.getByTestId("state")).toHaveTextContent("loading"); m.paper.error = new Error("offline"); view.rerender(<ExamSession slug="paper" onExit={m.exit} />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.paper.error = undefined; m.paper.data = { slug: "paper", titleEn: "Exam", titleVi: null, questions: [{ questionId: "q", skill: "grammar", stem: "?", optionA: "A", optionB: "B", optionC: "C", optionD: "D" }] }; view.rerender(<ExamSession slug="paper" onExit={m.exit} />); expect(screen.getByTestId("state")).toHaveTextContent("ready") }); it("submits, retries and exits", async () => { m.paper.data = { slug: "paper", titleEn: "Exam", titleVi: null, questions: [{ questionId: "q", skill: "grammar", stem: "?", optionA: "A", optionB: "B", optionC: "C", optionD: "D" }] }; m.grade.trigger.mockResolvedValue({ data: { gradePaper: { success: true, data: { score: 1, maxScore: 1, answers: [] } } } }); render(<ExamSession slug="paper" onExit={m.exit} />); fireEvent.click(screen.getByText("answer")); fireEvent.click(screen.getByText("submit")); await Promise.resolve(); fireEvent.click(screen.getByText("retry")); fireEvent.click(screen.getByText("exit")); expect(m.grade.trigger).toHaveBeenCalled(); expect(m.paper.mutate).toHaveBeenCalled(); expect(m.exit).toHaveBeenCalled() }) })
