/** @vitest-environment jsdom */
import { fireEvent, render, screen } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ paper: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, grade: { trigger: vi.fn(), isMutating: false } }))
vi.mock("next-intl", () => ({ useTranslations: () => (key: string) => key, useLocale: () => "en" }))
vi.mock("@/hooks/swr/useQueryPaperDetailSwr", () => ({ useQueryPaperDetailSwr: () => m.paper })); vi.mock("@/hooks/swr/useMutateGradePaperSwr", () => ({ useMutateGradePaperSwr: () => m.grade }))
type BaseProps = { readonly state: string; readonly props: { readonly title: string }; readonly on?: { readonly submit?: () => void; readonly previous?: () => void; readonly forward?: () => void; readonly exit?: () => void; readonly retry?: () => void; readonly back?: () => void } }
vi.mock("./component", () => ({ ExamSessionBase: (p: BaseProps) => <><output>{p.state}:{p.props.title}</output>{p.on?.submit && <button onClick={p.on.submit}>submit</button>}{p.on?.previous && <button onClick={p.on.previous}>previous</button>}{p.on?.forward && <button onClick={p.on.forward}>forward</button>}{p.on?.exit && <button onClick={p.on.exit}>exit</button>}{p.on?.retry && <button onClick={p.on.retry}>retry</button>}{p.on?.back && <button onClick={p.on.back}>back</button>}</> })); import { ExamSession } from "./index"
describe("ExamSession", () => { it("renders loading paper state", () => { m.paper = { data: undefined, error: undefined, mutate: vi.fn() }; render(<ExamSession slug="paper" onExit={vi.fn()} />); expect(screen.getByText(/loading/)).toBeTruthy() }); it("renders failed paper state", () => { m.paper = { data: null, error: undefined, mutate: vi.fn() }; render(<ExamSession slug="paper" onExit={vi.fn()} />); expect(screen.getByText(/failed/)).toBeTruthy() }); it("renders ready and exercises navigation and submit", async () => { m.paper = { data: { slug: "paper", titleEn: "Paper", titleVi: "Bai", questions: [{ questionId: "q1", skill: "arrays", stem: "Pick", optionA: "A", optionB: "B", optionC: "C", optionD: "D" }] }, error: undefined, mutate: vi.fn() }; m.grade = { trigger: vi.fn().mockResolvedValue({ data: { gradePaper: { success: true, data: { score: 1, maxScore: 1, answers: [] } } } }), isMutating: false }; render(<ExamSession slug="paper" onExit={vi.fn()} />); expect(screen.getByText(/ready/)).toBeTruthy(); fireEvent.click(screen.getByText("previous")); fireEvent.click(screen.getByText("forward")); fireEvent.click(screen.getByText("back")); fireEvent.click(screen.getByText("submit")); expect(m.grade.trigger).toHaveBeenCalled() }) })
