import { fireEvent, render, screen } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
const m = vi.hoisted(() => ({ programs: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, papers: { data: undefined as unknown, error: undefined as unknown, mutate: vi.fn() }, open: vi.fn(), premium: vi.fn() }))
vi.mock("next-intl", () => ({ useLocale: () => "en", useTranslations: () => (key: string) => key }))
vi.mock("@/hooks/swr/useQueryExamProgramsSwr", () => ({ useQueryExamProgramsSwr: () => m.programs }))
vi.mock("@/hooks/swr/useQueryPapersSwr", () => ({ useQueryPapersSwr: () => m.papers }))
type CatalogProps = { readonly state: string; readonly on: Record<string, (...args: ReadonlyArray<unknown>) => void> }
vi.mock("./component", () => ({ _ExamCatalog: ({ state, on }: CatalogProps) => <><output data-testid="state">{state}</output><button onClick={() => on["open:p1"]?.()}>open</button><button onClick={on.requestPremium}>premium</button><button onClick={on.retry}>retry</button></> }))
import { ExamCatalog } from "./index"
beforeEach(() => { vi.clearAllMocks(); m.programs.data = undefined; m.papers.data = undefined; m.programs.error = undefined; m.papers.error = undefined })
describe("ExamCatalog", () => { it("settles loading, empty, failed and ready", () => { const view = render(<ExamCatalog onOpenPaper={m.open} onRequestPremium={m.premium} />); expect(screen.getByTestId("state")).toHaveTextContent("loading"); m.programs.data = []; m.papers.data = []; view.rerender(<ExamCatalog onOpenPaper={m.open} onRequestPremium={m.premium} />); expect(screen.getByTestId("state")).toHaveTextContent("empty"); m.papers.error = new Error("offline"); view.rerender(<ExamCatalog onOpenPaper={m.open} onRequestPremium={m.premium} />); expect(screen.getByTestId("state")).toHaveTextContent("failed"); m.papers.error = undefined; m.papers.data = [{ id: "p1", slug: "paper", titleEn: "Paper", titleVi: null, descriptionEn: null, descriptionVi: null, level: "b1", questionCount: 10, isLocked: false, isDemo: false, programSlug: null }]; view.rerender(<ExamCatalog onOpenPaper={m.open} onRequestPremium={m.premium} />); expect(screen.getByTestId("state")).toHaveTextContent("ready") }); it("wires open, premium and retry actions", () => { m.programs.data = []; m.papers.data = [{ id: "p1", slug: "paper", titleEn: "Paper", titleVi: null, descriptionEn: null, descriptionVi: null, level: "b1", questionCount: 10, isLocked: false, isDemo: false, programSlug: null }]; render(<ExamCatalog onOpenPaper={m.open} onRequestPremium={m.premium} />); fireEvent.click(screen.getByText("open")); fireEvent.click(screen.getByText("premium")); fireEvent.click(screen.getByText("retry")); expect(m.open).toHaveBeenCalledWith("paper"); expect(m.premium).toHaveBeenCalled(); expect(m.programs.mutate).toHaveBeenCalled() }) })
