#!/usr/bin/env node
/**
 * Synchronize MiaMia FE's local API endpoint with the backend port registry.
 *
 * The backend owns the project offset. This repository consumes its resolved
 * web/API ports and writes only an ignored development env file; production
 * continues to receive its public API URL from deployment configuration.
 */

import {
    existsSync, readFileSync, writeFileSync,
} from "node:fs"
import {
    dirname, join, resolve,
} from "node:path"
import {
    fileURLToPath,
} from "node:url"

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const REGISTRY = resolve(REPO_ROOT, "../mia-mia-backend/metadata.json")
const ENV_TARGET = join(REPO_ROOT, ".env.development.local")
const MANIFEST = join(REPO_ROOT, "package.json")
const API_ENV = join(REPO_ROOT, "src/modules/api/env.ts")
const CHECK_ONLY = process.argv.includes("--check")
const MARKER = "# GENERATED by scripts/sync-ports.mjs -- do not edit by hand"

const die = (message) => {
    console.error(`sync:ports: ${message}`)
    process.exit(1)
}

if (!existsSync(REGISTRY)) {
    die(`missing backend registry at ${REGISTRY}`)
}

let registry
try {
    registry = JSON.parse(readFileSync(REGISTRY, "utf8"))
} catch (error) {
    die(`backend registry is not valid JSON: ${error.message}`)
}

const offset = registry.portOffset
const webPort = registry.ports?.web
const apiPort = registry.ports?.api
const colyseusPort = registry.ports?.colyseus
const webBasePort = registry.basePorts?.web
const apiBasePort = registry.basePorts?.api
const colyseusBasePort = registry.basePorts?.colyseus

for (const [name, value] of Object.entries({
    offset, webPort, apiPort, colyseusPort, webBasePort, apiBasePort, colyseusBasePort,
})) {
    if (!Number.isInteger(value)) {
        die(`metadata.json does not declare numeric ${name}`)
    }
}

if (webPort !== webBasePort + offset || apiPort !== apiBasePort + offset || colyseusPort !== colyseusBasePort + offset) {
    die("metadata.json resolved ports do not equal basePorts + portOffset")
}

const apiUrl = `http://localhost:${apiPort}/graphql`
const colyseusUrl = `ws://localhost:${colyseusPort}`
const generatedEnv = [
    MARKER,
    "#",
    `# source: ../mia-mia-backend/metadata.json (offset +${offset})`,
    `# web: http://localhost:${webPort}`,
    "",
    `NEXT_PUBLIC_API_GRAPHQL_BASE_URL=${apiUrl}`,
    `NEXT_PUBLIC_COLYSEUS_URL=${colyseusUrl}`,
    "",
].join("\n")

const drift = []
const scripts = JSON.parse(readFileSync(MANIFEST, "utf8")).scripts ?? {}
if (scripts.dev !== "node scripts/run-dev.mjs") {
    drift.push("package.json scripts.dev must delegate to scripts/run-dev.mjs")
}
const startPort = scripts.start?.match(/--port\s+(\d+)/)?.[1]
if (Number(startPort) !== webPort) {
    drift.push(`package.json scripts.start must use --port ${webPort}`)
}

const apiEnvSource = readFileSync(API_ENV, "utf8")
if (!apiEnvSource.includes(`http://localhost:${apiPort}/graphql`)) {
    drift.push(`src/modules/api/env.ts fallback must use ${apiUrl}`)
}
const gameEnvSource = readFileSync(join(REPO_ROOT, "src/modules/games/env.ts"), "utf8")
if (!gameEnvSource.includes(`ws://localhost:${colyseusPort}`)) drift.push(`src/modules/games/env.ts fallback must use ${colyseusUrl}`)

if (CHECK_ONLY) {
    if (!existsSync(ENV_TARGET) || readFileSync(ENV_TARGET, "utf8") !== generatedEnv) {
        drift.push(".env.development.local is missing or stale; run npm run sync:ports")
    }
} else {
    writeFileSync(ENV_TARGET, generatedEnv)
    console.log(`sync:ports: wrote .env.development.local for web :${webPort} -> API :${apiPort}`)
}

if (drift.length > 0) {
    for (const item of drift) {
        console.error(`sync:ports: drift: ${item}`)
    }
    process.exit(1)
}

console.log(`sync:ports: ok (web :${webPort}; API :${apiPort}; Colyseus :${colyseusPort}; offset +${offset})`)
