import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
const trigger = vi.fn()
vi.mock("next-intl", () => ({ useTranslations: () => (key: string) => key }))
vi.mock("@/hooks/swr/useMutateSubmitContactSwr", () => ({ useMutateSubmitContactSwr: () => ({ isMutating: false, trigger }) }))
type InquiryProps = { readonly state: string; readonly onSubmit: () => void; readonly onChange: (field: "name" | "email" | "message", value: string) => void; readonly onDismiss: () => void }
vi.mock("./component", () => ({ _WhiteLabelInquiryPanel: ({ state, onSubmit, onChange, onDismiss }: InquiryProps) => <><output data-testid="state">{state}</output><button onClick={() => onChange("name", "Ada Lovelace")}>name</button><button onClick={() => onChange("email", "ada@example.com")}>email</button><button onClick={() => onChange("message", "Please contact our team")}>message</button><button onClick={onSubmit}>submit</button><button onClick={onDismiss}>dismiss</button></> }))
import { WhiteLabelInquiryPanel } from "./index"
describe("WhiteLabelInquiryPanel", () => {
    it("validates before mutation and clears field errors as values change", async () => { const pending = vi.fn(); render(<WhiteLabelInquiryPanel onDismiss={vi.fn()} onPendingChange={pending} />); fireEvent.click(screen.getByText("submit")); expect(trigger).not.toHaveBeenCalled(); expect(screen.getByTestId("state")).toHaveTextContent("invalid"); fireEvent.click(screen.getByText("name")); fireEvent.click(screen.getByText("email")); fireEvent.click(screen.getByText("message")); await waitFor(() => expect(screen.getByTestId("state")).toHaveTextContent("invalid")) })
    it("reports success, server failure, thrown failure and dismissal", async () => { const dismiss = vi.fn(); const pending = vi.fn(); trigger.mockResolvedValueOnce({ data: { submitContact: { success: true } } }).mockResolvedValueOnce({ data: { submitContact: { success: false, message: "No" } } }).mockRejectedValueOnce(new Error("offline")); const view = render(<WhiteLabelInquiryPanel onDismiss={dismiss} onPendingChange={pending} />); fireEvent.click(screen.getByText("name")); fireEvent.click(screen.getByText("email")); fireEvent.click(screen.getByText("message")); fireEvent.click(screen.getByText("submit")); await new Promise((resolve) => setTimeout(resolve, 0)); expect(screen.getByTestId("state")).toHaveTextContent("succeeded"); fireEvent.click(screen.getByText("submit")); await new Promise((resolve) => setTimeout(resolve, 0)); expect(screen.getByTestId("state")).toHaveTextContent("failed"); fireEvent.click(screen.getByText("submit")); await new Promise((resolve) => setTimeout(resolve, 0)); expect(screen.getByTestId("state")).toHaveTextContent("failed"); fireEvent.click(screen.getByText("dismiss")); expect(dismiss).toHaveBeenCalledOnce(); expect(pending).toHaveBeenCalledWith(true); expect(pending).toHaveBeenCalledWith(false); view.unmount() })
})
